import = ["/home/arrahhal/.config/alacritty/themes/gruvbox-material-hard.toml"]

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"

[font.bold_italic]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "Backslash"
mods = "Alt"

[[keyboard.bindings]]
action = "SearchBackward"
key = "Backslash"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleMaximized"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "U"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "D"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "Hide"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mods = "Alt"

[[keyboard.bindings]]
action = "ClearHistory"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "Hide"
key = "Tab"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "S"
mods = "Alt"

[scrolling]
history = 10000

[window]
decorations = "none"

[window.dimensions]
columns = 190
lines = 48
